// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kokdhkczsbirxqqevoqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtva2Roa2N6c2JpcnhxcWV2b3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjkwNDEsImV4cCI6MjA2MzU0NTA0MX0.psnqbQFnBuKeY3sS1xW4okxjbeFibHzeKGMQ3yppW4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);